language: python

sudo: false

python:
    - "3.3"
    - "3.4"

services:
    - redis-server

before_install:
    - bash bin/check_signoff.sh
    - pip install -q flake8
    - flake8

install:
    - pip install -q -e .

before_script:
    - sh tests/start-neo4j.sh

script:
    - pip install -q coverage
    - coverage run test_suite.py

after_success:
    - pip install -q coveralls
    - coveralls > /dev/null
