language: python

python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"

env:
    - MYSQL_USER=travis MYSQL_HOST=127.0.0.1 POSTGRESQL_USER=postgres POSTGRESQL_HOST=127.0.0.1

services:
    - mongodb

before_install:
    - sh bin/check_signoff.sh
    - sh tests/start-neo4j.sh

install:
    - pip install -q coveralls --use-mirrors
    - pip install -r tests/requirements.txt
    - pip install flake8

before_script:
    - flake8 origins
    - mysql -u $MYSQL_USER < tests/data/chinook_mysql.sql > /dev/null
    - psql -U $POSTGRESQL_USER -c 'create database chinook' > /dev/null
    - psql -U $POSTGRESQL_USER -d chinook < tests/data/chinook_postgresql.sql > /dev/null
    - mongorestore --db chinook tests/data/mongodb > /dev/null

script:
    - coverage run test_suite.py

after_success:
    - coveralls
